apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-prod
  namespace: prod-env
spec:
  replicas: 2 # 운영 환경이니까 파드 2개!
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.24-alpine # 운영 환경은 버전이 고정된 가벼운 이미지를 씁니다!
        ports:
        - containerPort: 80
