apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dev
  namespace: dev-env
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        build: "2"
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:alpine
        ports:
        - containerPort: 80
